# Utilise l'image officielle Node.js recommandée par Microsoft
FROM mcr.microsoft.com/devcontainers/javascript-node:20

# Installe des dépendances supplémentaires ici si besoin
# RUN apt-get update && apt-get install -y <package> 