name: "Build and deploy web extensions"
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: "📦 Build web extensions"
    runs-on: ubuntu-latest
    steps:
      - name: "🚀 Checkout"
        uses: actions/checkout@v3

      - name: "👷 Install dependencies"
        run: npm install

      - name: "🔑 Add Gecko ID"
        run: |
          echo "AMO_GECKO_ID=${{ secrets.AMO_GECKO_ID }}" >> $GITHUB_ENV

      - name: "📄 Update Manifest with Gecko ID"
        run: npm run manifest:update

      - name: "📦 Build application"
        run: npm run build:all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: web-ext-artifacts
          path: web-ext-artifacts

  artifacts:
    name: "📦 Upload release artifacts"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "⬇️ Download Firefox artifact"
        uses: actions/download-artifact@v3
        with:
          name: web-ext-artifacts

      - name: "©️ Copy files"
        run: |
          cp ecoindex.fr-chrome.zip ecoindex-${{ github.ref_name }}-chrome.zip && \
          cp ecoindex.fr-firefox.zip ecoindex-${{ github.ref_name }}-firefox.zip

      - name: "⬆️ Upload release artifact"
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ecoindex-${{ github.ref_name }}-chrome.zip
            ecoindex-${{ github.ref_name }}-firefox.zip

  firefox:
    name: "🦊 Publish Firefox extension"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "⬇️ Download Firefox artifact"
        uses: actions/download-artifact@v3
        with:
          name: web-ext-artifacts

      - name: "💫 Publish firefox extension"
        uses: PlasmoHQ/bpp@v3
        with:
          artifact: ecoindex.fr-firefox.zip
          keys: ${{ secrets.BPP_KEYS_FIREFOX }}

  chrome:
    name: "🤖 Publish Chrome and edge extensions"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "⬇️ Download Chrome artifact"
        uses: actions/download-artifact@v3
        with:
          name: web-ext-artifacts

      - name: "💫 Publish chrome and edge extensions"
        uses: PlasmoHQ/bpp@v3
        with:
          artifact: ecoindex.fr-chrome.zip
          keys: ${{ secrets.BPP_KEYS_CHROME_EDGE }}
