name: "Lint Firefox web extension"
on:
  pull_request:

jobs:
  lint:
    name: "Linter"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Install dependencies"
        run: npm install

      - name: "Lint source code"
        run: npm run lint

      - name: "Lint extension"
        uses: kewisch/action-web-ext@v1
        with:
          cmd: lint
          source: src
          channel: listed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
